from django.urls import path
from . import views
from . import adminviews, teacherviews, Studentviews, EditResultVIewClass
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [
      path('demo', views.showDemoPage),
      path('', views.ShowLoginPage, name="show_login"),
      path('get_user_details', views.GetUserDetails),
      path('logout_user', views.logout_user, name="logout"),
      path('doLogin', views.doLogin, name="do_login"),
      path('admin_home',     adminviews.admin_home,     name="admin_home"),
      path('add_student',    adminviews.add_student,    name='add_student'),
      path('add_student_save', adminviews.add_student_save, name="add_student_save"),
      path('add_course',     adminviews.add_course,     name='add_course'),
      path('add_course_save', adminviews.add_course_save,name="add_course_save"),
      path('edit_course/<str:course_id>', adminviews.edit_course, name="edit_course"),
      path('edit_course_save', adminviews.edit_course_save, name="edit_course_save"),
      path('add_subject',    adminviews.add_subject,    name='add_subject'),
      path('add_subject_save', adminviews.add_subject_save, name="add_subject_save"),
      path('add_teacher',    adminviews.add_teacher,    name='add_teacher'),
      path('add_teacher_save', adminviews.add_teacher_save, name="add_teacher_save"),
      path('manage_teacher', adminviews.manage_teacher, name="manage_teacher"),
      path('manage_student', adminviews.manage_student, name="manage_student"),
      path('manage_course',  adminviews.manage_course,  name="manage_course"),
      path('manage_subject', adminviews.manage_subject, name="manage_subject"),
      path('edit_teacher/<str:teacher_id>', adminviews.edit_teacher, name="edit_teacher"),
      path('edit_teacher_save', adminviews.edit_teacher_save, name="edit_teacher_save"),
      path('edit_student/<str:student_id>', adminviews.edit_student, name="edit_student"),
      path('edit_student_save', adminviews.edit_student_save, name="edit_student_save"),
      path('edit_subject/<str:subject_id>', adminviews.edit_subject, name="edit_subject"),
      path('edit_subject_save', adminviews.edit_subject_save, name="edit_subject_save"),
      path('edit_course/<str:course_id>', adminviews.edit_course, name="edit_course"),
      path('edit_course_save', adminviews.edit_course_save, name="edit_course_save"),
      path('manage_session', adminviews.manage_session, name="manage_session"),
      path('add_session_save', adminviews.add_session_save, name="add_session_save"),
      path('signup_student', views.signup_student, name="signup_student"),
      path('signup_teacher', views.signup_teacher, name="signup_teacher"),
      path('signup_admin', views.signup_admin, name="signup_admin"),
      path('do_admin_signup', views.do_admin_signup, name="do_admin_signup"),
      path('do_teacher_signup', views.do_teacher_signup, name="do_staff_signup"),
      path('do_signup_student', views.do_signup_student, name="do_signup_student"),
      path('check_email_exist', adminviews.check_email_exist, name="check_email_exist"),
      path('check_username_exist', adminviews.check_username_exist, name="check_username_exist"),
      path('student_feedback_message', adminviews.student_feedback_message, name="student_feedback_message"),
      path('student_feedback_message_replied', adminviews.student_feedback_message_replied, name="student_feedback_message_replied"),
      path('teacher_feedback_message', adminviews.teacher_feedback_message, name="teacher_feedback_message"),
      path('teacher_feedback_message_replied', adminviews.teacher_feedback_message_replied, name="teacher_feedback_message_replied"),
      path('student_leave_view', adminviews.student_leave_view, name="student_leave_view"),
      path('teacher_leave_view', adminviews.teacher_leave_view, name="teacher_leave_view"),
      path('student_approve_leave/<str:leave_id>', adminviews.student_approve_leave, name="student_approve_leave"),
      path('student_disapprove_leave/<str:leave_id>', adminviews.student_disapprove_leave, name="student_disapprove_leave"),
      path('teacher_disapprove_leave/<str:leave_id>', adminviews.teacher_disapprove_leave, name="teacher_disapprove_leave"),
      path('teacher_approve_leave/<str:leave_id>', adminviews.teacher_approve_leave, name="teacher_approve_leave"),
      path('admin_view_attendance', adminviews.admin_view_attendance, name="admin_view_attendance"),
      path('admin_get_attendance_dates', adminviews.admin_get_attendance_dates, name="admin_get_attendance_dates"),
      path('admin_get_attendance_student', adminviews.admin_get_attendance_student, name="admin_get_attendance_student"),
      path('admin_profile', adminviews.admin_profile, name="admin_profile"),
      path('admin_profile_save', adminviews.admin_profile_save, name="admin_profile_save"),
      path('admin_send_notification_teacher', adminviews.admin_send_notification_teacher, name="admin_send_notification_teacher"),
      path('admin_send_notification_student', adminviews.admin_send_notification_student, name="admin_send_notification_student"),
      path('send_student_notification', adminviews.send_student_notification, name="send_student_notification"),
      path('send_teacher_notification', adminviews.send_teacher_notification, name="send_teacher_notification"),



      # Teacher urls
      path('teacher_home', teacherviews.teacher_home, name="teacher_home"),
      path('teacher_take_attendance', teacherviews.teacher_take_attendance, name="teacher_take_attendance"),
      path('teacher_update_attendance', teacherviews.teacher_update_attendance, name="teacher_update_attendance"),
      path('get_students', teacherviews.get_students, name="get_students"),
      path('get_attendance_dates', teacherviews.get_attendance_dates, name="get_attendance_dates"),
      path('get_attendance_student', teacherviews.get_attendance_student, name="get_attendance_student"),
      path('save_attendance_data', teacherviews.save_attendance_data, name="save_attendance_data"),
      path('save_updateattendance_data', teacherviews.save_updateattendance_data,
           name="save_updateattendance_data"),
      path('teacher_apply_leave', teacherviews.teacher_apply_leave, name="teacher_apply_leave"),
      path('teacher_apply_leave_save', teacherviews.teacher_apply_leave_save, name="teacher_apply_leave_save"),
      path('teacher_feedback', teacherviews.teacher_feedback, name="teacher_feedback"),
      path('teacher_feedback_save', teacherviews.teacher_feedback_save, name="teacher_feedback_save"),
      path('teacher_profile', teacherviews.teacher_profile, name="teacher_profile"),
      path('teacher_profile_save', teacherviews.teacher_profile_save, name="teacher_profile_save"),
      path('teacher_fcmtoken_save', teacherviews.teacher_fcmtoken_save, name="teacher_fcmtoken_save"),
      path('teacher_all_notification', teacherviews.teacher_all_notification, name="teacher_all_notification"),
      path('teacher_add_result', teacherviews.teacher_add_result, name="teacher_add_result"),
      path('save_student_result', teacherviews.save_student_result, name="save_student_result"),
      path('edit_student_result', EditResultVIewClass.EditResultViewClass, name="edit_student_result"),
      path('fetch_result_student', teacherviews.fetch_result_student, name="fetch_result_student"),
      path('start_live_classroom', teacherviews.start_live_classroom, name="start_live_classroom"),
      path('start_live_classroom_process', teacherviews.start_live_classroom_process,
           name="start_live_classroom_process"),

                    # student urls
      path('student_home', Studentviews.student_home, name="student_home"),
      path('student_view_attendance', Studentviews.student_view_attendance, name="student_view_attendance"),
      path('student_view_attendance_post', Studentviews.student_view_attendance_post,
           name="student_view_attendance_post"),
      path('student_apply_leave', Studentviews.student_apply_leave, name="student_apply_leave"),
      path('student_apply_leave_save', Studentviews.student_apply_leave_save, name="student_apply_leave_save"),
      path('student_feedback', Studentviews.student_feedback, name="student_feedback"),
      path('student_feedback_save', Studentviews.student_feedback_save, name="student_feedback_save"),
      path('student_profile', Studentviews.student_profile, name="student_profile"),
      path('student_profile_save', Studentviews.student_profile_save, name="student_profile_save"),
      path('student_fcmtoken_save', Studentviews.student_fcmtoken_save, name="student_fcmtoken_save"),
      path('firebase-messaging-sw.js', views.showFirebaseJS, name="show_firebase_js"),
      path('student_all_notification', Studentviews.student_all_notification, name="student_all_notification"),
      path('student_view_result', Studentviews.student_view_result, name="student_view_result"),
      path('join_class_room/<int:subject_id>/<int:session_year_id>', Studentviews.join_class_room,
           name="join_class_room"),
      path('testurl/', views.Testurl)
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)